import { auth } from "@/auth"
import { prisma } from "@/lib/prisma"
import { sendTelegramAlert } from "@/lib/telegram"
import { NextResponse } from "next/server"

function csvEscape(value: string | number | null | undefined) {
  const text = String(value ?? "")
  return `"${text.replaceAll('"', '""')}"`
}

function makeSimplePdf(title: string, lines: string[]) {
  const content = [
    "BT",
    "/F1 18 Tf",
    "50 780 Td",
    `(${title}) Tj`,
    "/F1 10 Tf",
    ...lines.flatMap((line) => ["0 -18 Td", `(${line.replace(/[()\\]/g, "")}) Tj`]),
    "ET",
  ].join("\n")

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
  ]

  let pdf = "%PDF-1.4\n"
  const offsets = [0]
  objects.forEach((object, index) => {
    offsets.push(pdf.length)
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`
  })
  const xref = pdf.length
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`
  })
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`

  return pdf
}

export async function GET(request: Request) {
  const session = await auth()

  if (!session?.user?.collegeId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const { searchParams } = new URL(request.url)
  const format = searchParams.get("format") === "pdf" ? "pdf" : "csv"

  const placements = await prisma.placement.findMany({
    where: { student: { collegeId: session.user.collegeId } },
    include: { student: true },
    orderBy: { dateOffered: "desc" },
  })

  await sendTelegramAlert(`Placement summary ${format.toUpperCase()} generated by ${session.user.email}`)

  if (format === "pdf") {
    const lines = placements.slice(0, 28).map((placement) => (
      `${placement.student.name} - ${placement.companyName} - ${placement.role} - ${placement.salary ?? "NA"} LPA`
    ))
    const pdf = makeSimplePdf("Skill Tank Placement Summary", lines)

    return new Response(pdf, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": "attachment; filename=placement-summary.pdf",
      },
    })
  }

  const rows = [
    ["Student", "Email", "Department", "Company", "Role", "Salary LPA", "Date Offered"],
    ...placements.map((placement) => [
      placement.student.name,
      placement.student.email,
      placement.student.department,
      placement.companyName,
      placement.role,
      placement.salary ?? "",
      placement.dateOffered.toISOString().slice(0, 10),
    ]),
  ]

  const csv = rows.map((row) => row.map(csvEscape).join(",")).join("\n")

  return new Response(csv, {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": "attachment; filename=placement-summary.csv",
    },
  })
}
