import { auth } from "@/auth"
import { prisma } from "@/lib/prisma"
import { sendTelegramAlert } from "@/lib/telegram"
import { NextResponse } from "next/server"

function csvEscape(value: string | number | null | undefined) {
  const text = String(value ?? "")
  return `"${text.replaceAll('"', '""')}"`
}

export async function GET() {
  const session = await auth()

  if (!session?.user?.collegeId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const enrollments = await prisma.enrollment.findMany({
    where: { student: { collegeId: session.user.collegeId } },
    include: { student: true, program: true },
    orderBy: { updatedAt: "desc" },
  })

  await sendTelegramAlert(`Cohort performance CSV generated by ${session.user.email}`)

  const rows = [
    ["Student", "Department", "Program", "Program Type", "Progress", "Status"],
    ...enrollments.map((enrollment) => [
      enrollment.student.name,
      enrollment.student.department,
      enrollment.program.name,
      enrollment.program.type,
      enrollment.progressPercentage,
      enrollment.status,
    ]),
  ]

  const csv = rows.map((row) => row.map(csvEscape).join(",")).join("\n")

  return new Response(csv, {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": "attachment; filename=cohort-performance.csv",
    },
  })
}
